name: 'Update Xcode Project Settings'
description: 'Updates Xcode project settings for code signing'
author: 'Carlos Li'
branding:
  icon: 'settings'
  color: 'blue'
inputs:
  project_path:
    description: 'Path to the Xcode project file'
    required: true
    default: 'ios/Runner.xcodeproj/project.pbxproj'
  provisioning_profile_specifier:
    description: 'Provisioning profile specifier'
    required: true
  code_sign_style:
    description: 'Code sign style'
    required: true
    default: 'Manual'
  code_sign_identity:
    description: 'Code sign identity'
    required: true
    default: 'iPhone Distribution'
  code_sign_identity_iphoneos:
    description: 'Code sign identity for iphoneos SDK'
    required: true
    default: 'iPhone Distribution'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install mod-pbxproj
      run: pip install pbxproj
      shell: bash

    - name: Update Xcode project settings
      run: python ${{ github.action_path }}/src/update_project.py
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
        PROVISIONING_PROFILE_SPECIFIER: ${{ inputs.provisioning_profile_specifier }}
        CODE_SIGN_STYLE: ${{ inputs.code_sign_style }}
        CODE_SIGN_IDENTITY: ${{ inputs.code_sign_identity }}
        CODE_SIGN_IDENTITY_IPHONEOS: ${{ inputs.code_sign_identity_iphoneos }}